### ISSUE TITLE
Release ?

### ISSUE THREAD

**Issue by remicollet** [udan11/sql-parser#15]
I think it could be a good idea to tag 1b2988f as 1.0.0 as this is the code bundled in phpMyAdmin 4.5.0, freshly released.

**Comment by udan11** [comment]
Done. Thanks!

**Comment by remicollet** [comment]
Notice, you have tagged 9098d37 when phpMyAdmin only use 1b2988f

**Comment by udan11** [comment]
Sorry, done.

**Comment by remicollet** [comment]
Thanks!
