### ISSUE TITLE
UPDATE statement setting column to NULL fails parsing

### ISSUE THREAD

**Issue by mikeedw** [udan11/sql-parser#21]
```sql
UPDATE `tableName` SET `colName` = NULL;
```

Gives me the following error:

`Line 1, col 35 at "NULL": Unrecognized keyword.`

This seems to be because of the following code in Components/SetOperation.php, which prevents NULL from being considered a valid assignment value:

```php
// No keyword is expected.
if (($token->type === Token::TYPE_KEYWORD) && ($token->flags & Token::FLAG_KEYWORD_RESERVED)) {
    break;
}
```

**Comment by udan11** [comment]
Fixed by 47d03c5dc614939b2df057b984544635ae6217db.
