### ISSUE TITLE
Please allow PHPUnit 5.x and enable travis for PHP 7.0

### ISSUE THREAD

**Issue by remicollet** [udan11/sql-parser#24]
Please revert a023393748617af9748d32489dacaeb587802bfe and use 

        "phpunit/phpunit": "~4.8 || ~5.1" 

With PHP 5.6

    $ phpunit --verbose
    PHPUnit 5.1.3 by Sebastian Bergmann and contributors.
    
    Runtime:       PHP 5.6.16
    Configuration: /dev/shm/extras/BUILD/sql-parser-47d03c5dc614939b2df057b984544635ae6217db/phpunit.xml
    
    ...............................................................  63 / 288 ( 21%)
    ............................................................... 126 / 288 ( 43%)
    ............................................................... 189 / 288 ( 65%)
    ............................................................... 252 / 288 ( 87%)
    ....................................                            288 / 288 (100%)
    
    Time: 1.67 seconds, Memory: 23.50Mb
    
    OK (288 tests, 640 assertions)

And with PHP 7.0

    $ phpunit --verbose
    PHPUnit 5.1.3 by Sebastian Bergmann and contributors.
    
    Runtime:       PHP 7.0.2RC1
    Configuration: /dev/shm/extras/BUILD/sql-parser-47d03c5dc614939b2df057b984544635ae6217db/phpunit.xml
    
    ...............................................................  63 / 288 ( 21%)
    ............................................................... 126 / 288 ( 43%)
    ............................................................... 189 / 288 ( 65%)
    ............................................................... 252 / 288 ( 87%)
    ....................................                            288 / 288 (100%)
    
    Time: 374 ms, Memory: 6.00Mb
    
    OK (288 tests, 640 assertions)

This also imply to drop composer.lock, but this file have no sense for a library.

**Comment by udan11** [comment]
Sorry, fixed in d888929271c41e7bd0e454acbbac08181b2b228c.
